# Generated by Django 3.1.1 on 2020-09-26 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('simID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.FloatField(max_length=50)),
                ('riskDecimal', models.FloatField(max_length=5)),
                ('rewardDecimal', models.FloatField(max_length=5)),
                ('winDecimal', models.FloatField(max_length=5)),
                ('lossDecimal', models.FloatField(max_length=5)),
                ('breakEvenDecimal', models.FloatField(max_length=5)),
                ('numOfTrades', models.IntegerField()),
                ('numOfSimulations', models.IntegerField()),
            ],
        ),
    ]
