# Generated by Django 3.1.1 on 2020-09-26 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('simID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maxPortfolio', models.FloatField(max_length=15)),
                ('minPortfolio', models.FloatField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='principal',
            field=models.FloatField(max_length=15),
        ),
    ]
